config/routes.rb
Rails.application.routes.draw do

  root 'keylists#index'
  get 'generate/generate'
  resources :keylists do
    resources :resources
  end

  resources :forbidden_resources

  Rails.application.routes.draw do
    mount Crono::Web, at: '/crono'
  end

end

app/models/forbidden_resource.rb
class ForbiddenResource < ActiveRecord::Base
end

app/controllers/forbidden_resources_controller.rb
class ForbiddenResourcesController < ApplicationController
  before_action :set_forbidden_resource, only: [:show, :edit, :update, :destroy]

  # GET /forbidden_resources
  # GET /forbidden_resources.json
  def index
    @forbidden_resources = ForbiddenResource.all
  end

  # GET /forbidden_resources/1
  # GET /forbidden_resources/1.json
  def show
  end

  # GET /forbidden_resources/new
  def new
    @forbidden_resource = ForbiddenResource.new
  end

  # GET /forbidden_resources/1/edit
  def edit
  end

  # POST /forbidden_resources
  # POST /forbidden_resources.json
  def create
    @forbidden_resource = ForbiddenResource.new(forbidden_resource_params)

    respond_to do |format|
      if @forbidden_resource.save
        format.html { redirect_to @forbidden_resource, notice: 'Forbidden resource was successfully created.' }
        format.json { render :show, status: :created, location: @forbidden_resource }
      else
        format.html { render :new }
        format.json { render json: @forbidden_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forbidden_resources/1
  # PATCH/PUT /forbidden_resources/1.json
  def update
    respond_to do |format|
      if @forbidden_resource.update(forbidden_resource_params)
        format.html { redirect_to @forbidden_resource, notice: 'Forbidden resource was successfully updated.' }
        format.json { render :show, status: :ok, location: @forbidden_resource }
      else
        format.html { render :edit }
        format.json { render json: @forbidden_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forbidden_resources/1
  # DELETE /forbidden_resources/1.json
  def destroy
    @forbidden_resource.destroy
    respond_to do |format|
      format.html { redirect_to forbidden_resources_url, notice: 'Forbidden resource was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forbidden_resource
      @forbidden_resource = ForbiddenResource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forbidden_resource_params
      params.require(:forbidden_resource).permit(:name)
    end
end

app/helpers/forbidden_resources_helper.rb
module ForbiddenResourcesHelper
end

app/views/forbidden_resources/_form.html.erb
<%= form_for(@forbidden_resource) do |f| %>
  <% if @forbidden_resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forbidden_resource.errors.count, "error") %> prohibited this forbidden_resource from being saved:</h2>

      <ul>
      <% @forbidden_resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forbidden_resources/edit.html.erb
<h1>Editing Forbidden Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @forbidden_resource %> |
<%= link_to 'Back', forbidden_resources_path %>

app/views/forbidden_resources/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to '<<Ресурсы', keylists_path %>

<h1>Listing Forbidden Resources</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forbidden_resources.each do |forbidden_resource| %>
      <tr>
        <td><%= forbidden_resource.name %></td>
        <td><%= link_to 'Show', forbidden_resource %></td>
        <td><%= link_to 'Edit', edit_forbidden_resource_path(forbidden_resource) %></td>
        <td><%= link_to 'Destroy', forbidden_resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forbidden resource', new_forbidden_resource_path %>

app/views/forbidden_resources/new.html.erb
<h1>New Forbidden Resource</h1>

<%= render 'form' %>

<%= link_to 'Back', forbidden_resources_path %>

app/views/forbidden_resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @forbidden_resource.name %>
</p>

<%= link_to 'Edit', edit_forbidden_resource_path(@forbidden_resource) %> |
<%= link_to 'Back', forbidden_resources_path %>