config/routes.rb
Rails.application.routes.draw do

  root 'keylists#index'
  get 'generate/generate'
  resources :keylists do
    resources :resources
  end

  resources :forbidden_resources

  Rails.application.routes.draw do
    mount Crono::Web, at: '/crono'
  end

end

app/views/resources/_form.html.erb
<%= form_for([@keylist, @resource]) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Domain</h1>

<%= render 'form' %>

<%= link_to 'Show', keylist_resource_path(@keylist,@resource) %> |
<%= link_to 'Back', keylist_resource_path(@keylist,@resource) %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список ресурсов для ключевых слов: </h1>

<h2><%= @keylist.keywords %></h2>

<%= link_to '<-- Назад к ключевым словам', keylists_path %>

<h1>Активные:</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>


      <th>Active from</th>
      <th>Banned at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @active_resources.each do |resource| %>
      <tr>
        <td><%= resource.name %></td>


        <td><%= resource.active_from %></td>
        <td><%= resource.banned_at %></td>
        <td><%= link_to 'Show', keylist_resource_path(@keylist ,resource) %></td>
        <td><%= link_to 'Edit', edit_keylist_resource_path(@keylist ,resource) %></td>
        <td><%= link_to 'Destroy', keylist_resource_path(@keylist ,resource), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<h1>В очереди</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>


    <th>Active from</th>
    <th>Banned at</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @pending_resources.each do |resource| %>
      <tr>
        <td><%= resource.name %></td>


        <td><%= resource.active_from %></td>
        <td><%= resource.banned_at %></td>
        <td><%= link_to 'Show', keylist_resource_path(@keylist ,resource) %></td>
        <td><%= link_to 'Edit', edit_keylist_resource_path(@keylist ,resource) %></td>
        <td><%= link_to 'Destroy', keylist_resource_path(@keylist ,resource), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>


<%= link_to 'Добавить новый ресурс', new_keylist_resource_path %><br> <br><br>


<h1>Забаненные</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>


    <th>Active from</th>
    <th>Banned at</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @banned_resources.each do |resource| %>
      <tr>
        <td><%= resource.name %></td>

        <td><%= resource.active_from %></td>
        <td><%= resource.banned_at %></td>
        <td><%= link_to 'Show', keylist_resource_path(@keylist ,resource) %></td>
        <td><%= link_to 'Edit', edit_keylist_resource_path(@keylist ,resource) %></td>
        <td><%= link_to 'Destroy', keylist_resource_path(@keylist ,resource), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>

</table>
<br><br>

app/views/resources/new.html.erb
<h1>New Domain</h1>

<%= render 'form' %>

<%= link_to 'Back', keylist_resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>


<p>
  <strong>Status:</strong>
  <%= @resource.status %>
</p>

<p>
  <strong>Active from:</strong>
  <%= @resource.active_from %>
</p>

<p>
  <strong>Banned at:</strong>
  <%= @resource.banned_at %>
</p>

<%= link_to 'Edit', edit_keylist_resource_path(@keylist,@resource) %> |
<%= link_to 'Back', keylist_resources_path(@keylist,@resource) %>