config/routes.rb
Rails.application.routes.draw do

  root 'keylists#index'
  get 'generate/generate'
  resources :keylists do
    resources :resources
  end

  resources :forbidden_resources

  Rails.application.routes.draw do
    mount Crono::Web, at: '/crono'
  end

end

app/models/keylist.rb
class Keylist < ActiveRecord::Base

  has_many :resources, dependent: :destroy

  # accepts_nested_attributes_for :resources,
  #                               :reject_if => lambda { |resource| resource[:name].blank? }

end

app/controllers/keylists_controller.rb
class KeylistsController < ApplicationController
  before_action :set_keylist, only: [:show, :edit, :update, :destroy]

  # GET /keylists
  # GET /keylists.json
  def index
    @keylists = Keylist.all.eager_load(:resources) #.where("resources.status = 'active'")
    #keylists = Keylist.where(active: true).eager_load(:resources).where("resources.status = 'active'")
  end

  # GET /keylists/1
  # GET /keylists/1.json
  def show
  end

  # GET /keylists/new
  def new
    @keylist = Keylist.new
    #5.times { @keylist.resources.new }
  end

  # GET /keylists/1/edit
  def edit
    #5.times { @keylist.resources.build }
  end

  # POST /keylists
  # POST /keylists.json
  def create
    @keylist = Keylist.new(keylist_params)

    respond_to do |format|
      if @keylist.save
        format.html { redirect_to @keylist, notice: 'Keylist was successfully created.' }
        format.json { render :show, status: :created, location: @keylist }
      else
        format.html { render :new }
        format.json { render json: @keylist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keylists/1
  # PATCH/PUT /keylists/1.json
  def update
    respond_to do |format|
      if @keylist.update(keylist_params)
        format.html { redirect_to @keylist, notice: 'Keylist was successfully updated.' }
        format.json { render :show, status: :ok, location: @keylist }
      else
        format.html { render :edit }
        format.json { render json: @keylist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keylists/1
  # DELETE /keylists/1.json
  def destroy
    @keylist.destroy
    respond_to do |format|
      format.html { redirect_to keylists_url, notice: 'Keylist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keylist
      @keylist = Keylist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def keylist_params
      params.require(:keylist).permit(:keywords, :active, resources: [:id, :name] )
    end
end

app/helpers/keylists_helper.rb
module KeylistsHelper

  def current_keylist_message(keylist)

    if keylist.active
      #active_resource = keylist.resources.where(status: 'active')[0]
      active_resource = keylist.resources.to_a.select { |resource| resource.status == 'active' }.first

      if active_resource.blank?
        #pending_resource = keylist.resources.where(status: 'pending')[0]
        pending_resource = keylist.resources.to_a.select { |resource| resource.status == 'pending' }.first
        if pending_resource.blank?
          return 'Внимание, для ключевых слов не заданны адреса'
        else
          return 'Ресурс ожидает обработки'
        end
      else
        return active_resource.name
      end
    else
      'Набор ключевых слов не активен'
    end
  end

  def resource_in_queue_cnt(keylist)
    resources = keylist.resources.to_a.select { |r| r.status == 'pending' }
    resources.count
  end

end

app/views/keylists/_form.html.erb
<%= form_for(@keylist) do |f| %>
  <% if @keylist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keylist.errors.count, "error") %> prohibited this keylist from being saved:</h2>

      <ul>
      <% @keylist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :keywords %><br>
    <%= f.text_area :keywords %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
    <!--    he -->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keylists/edit.html.erb
<h1>Editing Keylist</h1>

<%= render 'form' %>

<%= link_to 'Show', @keylist %> |
<%= link_to 'Back', keylists_path %>

app/views/keylists/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Запрещенные ресурсы>>', forbidden_resources_path %>

<h1>Список ключевых слов:</h1>

<table>
  <thead>
    <tr>
      <th>Keywords</th>
      <th>Active</th>
      <th>Текущий активный домен: </th>
      <th>Ресурсов в очереди: </th>
      <th colspan="4"></th>

    </tr>
  </thead>

  <tbody>
    <% @keylists.each do |keylist| %>
      <tr>
        <td><%= keylist.keywords %></td>
        <td><%= keylist.active %></td>
        <td><%= current_keylist_message(keylist) %></td>
        <td><%= resource_in_queue_cnt(keylist) %></td>
        <td><%= link_to 'Show', keylist %></td>
        <td><%= link_to 'Редактировать список доменов', keylist_resources_path(keylist) %></td>
        <td><%= link_to 'Edit', edit_keylist_path(keylist) %></td>
        <td><%= link_to 'Destroy', keylist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить список ключевых слов', new_keylist_path %>

<br><br><br>
<%= link_to 'Генерировать скрипт сейчас -> ', generate_generate_path %>

app/views/keylists/new.html.erb
<h1>New Keylist</h1>

<%= render 'form' %>

<%= link_to 'Back', keylists_path %>

app/views/keylists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Keywords:</strong>
  <%= @keylist.keywords %>
</p>

<p>
  <strong>Active:</strong>
  <%= @keylist.active %>
</p>

<%= link_to 'Редактировать ресурсы ->', keylist_resources_path(@keylist) %><br><br>

<%= link_to 'Edit', edit_keylist_path(@keylist) %> |
<%= link_to 'Back', keylists_path %>